# Change these first
owner: Th7bo # Your GitHub organization or username, where this repository lives
repo: Depthful_Uptime # The name of this repository

sites:
  - name: th7bo.com
    url: https://www.th7bo.com
  - name: panel.th7bo.com
    url: https://panel.th7bo.com
  - name: node3.th7bo.com
    url: node3.th7bo.com
  - name: Depthful server
    url: https://api.mcsrvstat.us/3/play.th7bo.com
    __dangerous__body_down: '"online": false'
assignees:
  - Th7bo

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.th7bo.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Th7bo Status
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
